---

- hosts: MONGODB_PRIMARY
  roles:
   - { role: role-mongodb-primary,   
       mongodb_work_path: /home/core/mongo,
       mongodb_deploy_config: true,
       mongo_admin_user: siteAdmin,
       mongo_admin_pass: admin,
       mongo_db_name: soc-db,
       mongo_root_user: siteRoot, 
       mongo_root_pass: root
     }

- hosts: NODEJS_API
  roles:
   - { role: role-nodejs-api,
       nodejs_deploy_config: true,
       nodejs_work_path: /home/core,
       soc_api_logpath: /home/core/soc-api-log,
       mongodb_ip_address: "{{ groups['MONGODB_PRIMARY'][0] }}",
       soc_api_version: v1.2.1,
       angular_ihm_domain: "{{ groups['ANGULAR_IHM'][0] }}",
       angular_ihm_ip: "{{ groups['ANGULAR_IHM'][0] }}"
     }

- hosts: ANGULAR_IHM
  roles:
   - { role: role-soc-ihm, 
       nginx_log_path: /var/log/nginxlogs, 
       application_directory: /usr/share/nginx,
       soc_ihm_version: v2.0.0,
       mongodbprimary_ip_address: "{{ groups['MONGODB_PRIMARY'][0] }}",
       mongodbsecondary_ip_address: "{{ groups['MONGODB_SECONDARY'][0] }}",
       nodejs_api_ip:  "{{ groups['NODEJS_API'][0] }}",
       angular_ihm_ip: "{{ groups['ANGULAR_IHM'][0] }}",  
       nginx_deploy_config: true 
     }
