---
# vars file for role-soc-ihm

#binary_path: /usr/bin/nodejs
#npm_pkg_name: npm
epel_pkg_name: epel-release
nginx_pkg_name: nginx
fileconf_path: /etc/nginx/nginx.conf
fileservice_path: /lib/systemd/system/nginx.service
directory_app_work_path: /usr/share/appbuild_ihm
application_port: 80
application_dist_path: /usr/share/nginx/soc-ihm/dist
